name:                conduit-server
version:             0.1.0.0
github:              "nodew/haskell-realworld-example"
license:             BSD3
author:              "Qiao Wang"
maintainer:          "wangqiao11@hotmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nodew/haskell-realworld-example#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- base64-bytestring
- bytestring
- cryptonite
- data-default
- extra
- file-embed
- hasql
- hasql-migration
- hasql-pool
- hasql-transaction
- jose
- lens
- memory
- mtl
- random
- rel8
- rio
- servant-auth
- servant-auth-server
- servant-server
- text
- time
- transformers
- uuid
- wai
- wai-extra
- wai-logger
- warp

default-extensions:
- DataKinds
- DerivingStrategies
- DeriveAnyClass
- NoImplicitPrelude
- OverloadedStrings
- TypeFamilies
- TypeOperators

library:
  source-dirs: src
  language: GHC2021

executables:
  conduit-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - conduit-server
    language: GHC2021

tests:
  conduit-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - http-types
    - hspec
    - hspec-wai
    - QuickCheck
    - conduit-server
    language: GHC2021
